DELETE FROM  JAVA_SCRIPT_FRAMEWORK_VERSIONS;
DELETE FROM  JAVA_SCRIPT_FRAMEWORK;

INSERT INTO JAVA_SCRIPT_FRAMEWORK (ID, HYPE_LEVEL, NAME) VALUES ('1', 'SOLID', 'Angular');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('1', '1.0.0');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('1', '1.2.0');

INSERT INTO JAVA_SCRIPT_FRAMEWORK (ID, HYPE_LEVEL, NAME) VALUES ('2', 'SENSATIONAL', 'React');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('2', '3.0.0');

INSERT INTO JAVA_SCRIPT_FRAMEWORK (ID, HYPE_LEVEL, NAME) VALUES ('3', 'LETDOWN', 'jQuery');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('3', '.2.1');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('3', '"3.2.0');

INSERT INTO JAVA_SCRIPT_FRAMEWORK (ID, HYPE_LEVEL, NAME) VALUES ('4', 'SENSATIONAL', 'Backbone');
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSIONS (JAVA_SCRIPT_FRAMEWORK_ID, VERSION) VALUES ('4', '3.0.0');