spring:
  datasource:
    url: jdbc:h2:mem:frameworkdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: false
      ddl-auto: create-drop #only for H2 db
  h2:
    console:
      enabled: true